- hosts: 'homework'
  remote_user: 'ubuntu'
  tasks:
  # install docker engine
  - name: 'apt update'
    apt:
      update_cache: 'yes'
    become: 'yes'

  - name: 'install packages'
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    become: 'yes'

  - name: 'add docker gpg key'
    apt_key:
      url: 'https://download.docker.com/linux/ubuntu/gpg'
      state: 'present'
    become: 'yes'

  - name: 'add docker repository'
    apt_repository:
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
      state: 'present'
    become: 'yes'

  - name: 'apt update'
    apt:
      update_cache: 'yes'
    become: 'yes'

  - name: 'reconfigure dpkg'
    shell: |
      dpkg --configure -a
    when: True
    become: 'yes'

  - name: 'apt upgrade'
    apt:
      upgrade: 'yes'
    become: 'yes'

  - name: 'install docker engine and docker compose'
    apt:
      force: 'yes'
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    become: 'yes'

  # post install
  - name: 'add group docker'
    group:
      name: 'docker'
      state: 'present'
    become: 'yes'

  - name: 'add user to group docker'
    user:
      name: 'ubuntu'
      groups: 'docker'
      append: 'yes'
    become: 'yes'

  # after post install tasks, the machine needs to be restarted
  - name: 'restart instances'
    reboot:
      reboot_timeout: 1800
    become: 'yes'

- hosts: 'mysql'
  remote_user: 'ubuntu'
  tasks:
  - name: 'pull mysql image'
    docker_image:
      name: 'mysql:8.0.19'
      source: 'pull'

  - name: 'run mysql container'
    docker_container:
      image: 'mysql:8.0.19'
      name: 'database'
      ports:
      - '3306:3306'
      command: 'mysqld --default-authentication-plugin=mysql_native_password'
      restart_policy: 'always'
      recreate: 'yes'
      volumes:
      - 'mysql_data:/var/lib/mysql'
      env:
        MYSQL_ROOT_PASSWORD: 'somewordpress'
        MYSQL_DATABASE: 'wordpress'
        MYSQL_USER: 'wordpress'
        MYSQL_PASSWORD: 'wordpress'

- hosts: 'wordpress'
  remote_user: 'ubuntu'
  tasks:
  - name: 'pull wordpress image'
    docker_image:
      name: 'wordpress:5.4.2'
      source: 'pull'

  - name: 'run wordpress container'
    docker_container:
      image: 'wordpress:5.4.2'
      name: 'web'
      ports:
      - '80:80'
      restart_policy: 'always'
      recreate: 'yes'
      env:
        WORDPRESS_DB_HOST: '{{ groups["mysql"][0] }}'
        WORDPRESS_DB_NAME: 'wordpress'
        WORDPRESS_DB_USER: 'wordpress'
        WORDPRESS_DB_PASSWORD: 'wordpress'
