- hosts: local
  gather_facts: True
  tasks:
  - name: get hostname
    debug:
      var: inventory_hostname
  - name: install jq package
    apt:

  - name: restart sshd
    service:
      name: sshd
      state: restarted
    become: yes
    become_method: sudo
